# Generated by Django 5.2.17 on 2026-09-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
