# Generated by Django 5.2.17 on 2026-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content_format",
            field=models.CharField(
                choices=[("markdown", "Markdown"), ("html", "Custom HTML")],
                default="markdown",
                help_text="How `body` is interpreted when the public site renders this page — see this module's docstring.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Markdown (rendered to sanitized HTML at read time — see apps/pages/rendering.py), or, when content_format is 'html', the author's own document served verbatim inside a sandboxed frame.",
            ),
        ),
    ]
