# Generated by Django 5.2.17 on 2026-09-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="page_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
