# Generated by Django 5.2.17 on 2026-08-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
