# Generated by Django 5.2.17 on 2026-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="sightings_public_by_default",
            field=models.BooleanField(
                default=True,
                help_text="New sightings logged on this property start with this as their public/private value (still overridable per sighting). Flip to off for a property where public location data could put sensitive species/sites at risk.",
            ),
        ),
    ]
