# Generated by Django 5.2.17 on 2026-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_backfill_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
