# Generated by Django 5.2.17 on 2026-08-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_property_deleted_at"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="landing_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Org-level page shown at the public URL root. Leave unset for the built-in Explore view.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pages.page",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="landing_page",
            field=models.ForeignKey(
                blank=True,
                help_text="This property's page shown at its public URL root. Leave unset for the built-in Explore view.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pages.page",
            ),
        ),
    ]
