# Generated by Django 5.2.17 on 2026-08-31 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_organization_landing_page_property_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="theme_accent_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_background_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_font",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sans", "Sans-serif"),
                    ("serif", "Serif"),
                    ("rounded", "Rounded"),
                    ("monospace", "Monospace"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_header_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_header_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_primary_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_accent_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_background_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_font",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sans", "Sans-serif"),
                    ("serif", "Serif"),
                    ("rounded", "Rounded"),
                    ("monospace", "Monospace"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_header_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_header_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="theme_primary_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex color, e.g. #2f6f4f.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
            ),
        ),
    ]
