# Generated by Django 5.2.17 on 2026-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_organization_theme_accent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="custom_html_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Whether this organization may author custom-HTML pages (when the deployment enables the feature at all).",
            ),
        ),
    ]
