# Generated by Django 5.2.17 on 2026-08-07 17:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0001_initial"),
        ("species", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When the sighting occurred, which may differ from when it was logged."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Sightings are public by default; uncheck to make this one record private. NOTE: no auto-private default yet for sensitive/at-risk species — see /docs/open-questions.md ('Sensitive sighting default behavior'). Set this manually for any sighting where public location data could cause harm.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sightings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — a sighting's point may or may not fall within a drawn property boundary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sightings",
                        to="accounts.property",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sightings",
                        to="species.species",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="SightingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField()),
                ("content_type", models.CharField(max_length=100)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sighting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="sightings.sighting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SightingActivityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sighting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sightings.sighting",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sighting", "activity"),
                        name="unique_sighting_activity_link",
                    )
                ],
            },
        ),
    ]
