# Generated by Django 5.2.17 on 2026-08-07 17:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField()),
                ("content_type", models.CharField(max_length=100)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivitySpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planted", "Planted"),
                            ("treated_target", "Treated / targeted"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        help_text="Free-text fallback/detail alongside the structured pick (e.g. method/product used for a treatment).",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activity species",
            },
        ),
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_planned", models.BooleanField(default=False)),
                ("is_done", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["organization_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("seeding", "Seeding"),
                            ("planting", "Planting"),
                            ("treatment", "Treatment"),
                            ("removal", "Removal"),
                            ("monitoring", "Monitoring"),
                            ("maintenance", "Maintenance"),
                            ("intervention", "Intervention (general)"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("date_planned", models.DateField(blank=True, null=True)),
                ("date_done", models.DateField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Activities are public by default; uncheck to make this one record private, overriding the account default.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="accounts.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
