# Generated by Django 5.2.17 on 2026-08-07 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0001_initial"),
        ("sightings", "0001_initial"),
        ("species", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="sightings",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_activities",
                through="sightings.SightingActivityLink",
                to="sightings.sighting",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityphoto",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activityspecies",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="activities.activity"
            ),
        ),
        migrations.AddField(
            model_name="activityspecies",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="species.species"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                related_name="activities",
                through="activities.ActivitySpecies",
                to="species.species",
            ),
        ),
        migrations.AddField(
            model_name="workflowstate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_states",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="activities.workflowstate",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_state_name_per_organization",
            ),
        ),
    ]
