# Generated by Django 5.2.17 on 2026-08-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_name", models.CharField(max_length=255)),
                ("scientific_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "species",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "common_name"),
                        name="unique_common_name_per_organization",
                    )
                ],
            },
        ),
    ]
